print('======= D E S A F I O   0 2 =======')
dia = input('Digite o dia do seu nascimento: ')
mes = input('Digite o mês do seu nascimento: ')
ano = input('Digite o ano do seu nascumento: ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano)
